# Generated by Django 5.2.16 on 2026-07-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalproduct_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='capacity_units',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum stock capacity, in your chosen unit (e.g. pallets, cubic meters)', null=True),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch Storage'), ('transit', 'Transit/Staging'), ('cold_storage', 'Cold Storage')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_units',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum stock capacity, in your chosen unit (e.g. pallets, cubic meters)', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'Main Warehouse'), ('branch', 'Branch Storage'), ('transit', 'Transit/Staging'), ('cold_storage', 'Cold Storage')], default='main', max_length=20),
        ),
    ]
