# Generated by Django 5.2.16 on 2026-07-24 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicalstockadjustment_stockadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['expiry_date'], name='core_batch_expiry__7dbedc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product', 'warehouse'], name='core_batch_product_bb1983_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='core_produc_barcode_5cc7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'warehouse'], name='core_stockm_product_6f2a45_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['timestamp'], name='core_stockm_timesta_82d7df_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status'], name='core_stockt_status_b0fb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['source_warehouse', 'destination_warehouse'], name='core_stockt_source__08ee88_idx'),
        ),
    ]
