# Generated by Django 5.2.16 on 2026-07-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_batch_core_batch_expiry__7dbedc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
