# Generated by Django 5.2.16 on 2026-08-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalwarehouse',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
