# Generated by Django 5.2.16 on 2026-08-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('org_admin', 'Organization Administrator'), ('branch_manager', 'Branch Manager'), ('warehouse_manager', 'Warehouse Manager'), ('inventory_officer', 'Inventory Officer'), ('procurement_officer', 'Procurement Officer'), ('sales_staff', 'Sales Staff (Cashier)'), ('accountant', 'Accountant'), ('vendor', 'Vendor (Portal)'), ('executive', 'Executive (Read-only Dashboard)'), ('customer', 'Customer')], default='sales_staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('org_admin', 'Organization Administrator'), ('branch_manager', 'Branch Manager'), ('warehouse_manager', 'Warehouse Manager'), ('inventory_officer', 'Inventory Officer'), ('procurement_officer', 'Procurement Officer'), ('sales_staff', 'Sales Staff (Cashier)'), ('accountant', 'Accountant'), ('vendor', 'Vendor (Portal)'), ('executive', 'Executive (Read-only Dashboard)'), ('customer', 'Customer')], default='sales_staff', max_length=30),
        ),
    ]
