# Generated by Django 5.2.16 on 2026-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
