# Generated by Django 5.2.16 on 2026-07-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
