# Generated by Django 5.2.16 on 2026-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_historicalpurchaseorder_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvendor',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalvendor',
            name='performance_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
